package com.kanga.kickrushapi.common;

public enum ErrorCode {
    INVALID_PARAMETER,
    RELEASE_NOT_STARTED,
    RELEASE_ENDED,
    UNAUTHORIZED,
    INVALID_CREDENTIALS,
    TOKEN_EXPIRED,
    FORBIDDEN,
    SHOE_NOT_FOUND,
    RELEASE_NOT_FOUND,
    ORDER_NOT_FOUND,
    STOCK_INSUFFICIENT,
    DUPLICATE_ORDER,
    DUPLICATE_EMAIL,
    ORDER_NOT_CANCELLABLE,
    LOCK_TIMEOUT
}
